### ISSUE TITLE
Need new irelia skin!

### ISSUE THREAD

**Issue by Sniper5224** [hydy100/Sakura#19]
If avalible, wish to update to new version 🙏

**Comment by kulaid** [comment]
chibi katarina + skins is also missing

**Comment by Serendipitymayi** [comment]
This version of the file entering the game will cause the game to crash

**Comment by pqh040926** [comment]
> This version of the file entering the game will cause the game to crash

Have you solved it? I'm running into this issue as well

**Comment by Sniper5224** [comment]
I dont have crash issue, but i dont see the new irelia and katarina in the new riot_release version :(

**Comment by kulaid** [comment]
when i download the latest release it downloads the November 22nd release hence why the 2 new skins aren't showing up https://i.imgur.com/cEZvqpX.png

**Comment by Sniper5224** [comment]
The new version works very well!! thx a lot ❤️
